name: "Format Golang directories"
description: "Action designed to format the Golang code"

inputs:
  go-version:
    description: "The version of the Golang compiler"
  branch_name:
    description: "The branch where to push the formatted code"
  working_directory:
    description: "The path of the Golang code"

runs:
  using: "composite"
  steps:
    - name: Setup Golang
      id: setup
      uses: actions/setup-go@v2
      with:
        go-version: "${{ inputs.go-version }}"
    - name: Golang format code
      id: format
      env:
        WORKING_DIRECTORY: "${{ inputs.working_directory }}"
      run: |
        "${{ github.action_path }}/golang_fmt.sh"
      shell: bash
    - name: Push code
      id: push
      env:
        BRANCH_NAME: "${{ inputs.branch_name }}"
        WORKING_DIRECTORY: "${{ inputs.working_directory }}"
      run: |
        "${{ github.action_path }}/../ga-common/push_code.sh"
      shell: bash
