name: "Build a package"
description: "Action designed to build a Linux package (DEB or RPM)"

inputs:
  package_filename:
    description: "The name of the package to build"
  package_version:
    description: "The version of the package to build"
  package_type:
    description: "The type of package to use (DEB or RPM)"
  working_directory:
    description: "The path of the shell code"

runs:
  using: "composite"
  steps:
    - name: Shell check code
      id: check
      env:
        PACKAGE_FILENAME: "${{ inputs.package_filename }}"
        PACKAGE_VERSION: "${{ inputs.package_version }}"
        PACKAGE_TYPE: "${{ inputs.package_type }}"
        WORKING_DIRECTORY: "${{ inputs.working_directory }}"
      run: |
        "${{ github.action_path }}/build_package.sh"
      shell: bash
