name: shell-worfklow

on:
  push:
    branches:
    - main
    - staging
    - develop
    paths:
    - "**"
    - "!.github/params/**"
    - "!.github/scripts/**"
    - "!.github/workflows/**"

jobs:
  init:
    name: Initialization
    runs-on: ubuntu-latest
    outputs:
      threads: ${{ steps.init.outputs.threads }}

      dir_list_dev: ${{ steps.init.outputs.dir_list_dev }}
      dir_list_test: ${{ steps.init.outputs.dir_list_test }}
      dir_list_prod: ${{ steps.init.outputs.dir_list_prod }}

      execute_check_and_format: ${{ steps.init.outputs.execute_check_and_format }}
      execute_test: ${{ steps.init.outputs.execute_test }}
      execute_deploy: ${{ steps.init.outputs.execute_deploy }}

      sha7: ${{ steps.init.outputs.sha7 }}
      cache_key: ${{ steps.init.outputs.cache_key }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          path: "sources/"
          submodules: true
      - name: Init
        id: init
        uses: Zidmann/github-actions-template-prototype/ga-init@main
        with:
          workflow_name: "shell"
          env_path: "sources/.github/params/shell.env"
      - name: Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: "sources/"
          key: "${{ steps.init.outputs.cache_key }}"

  dev-check:
    name: Check directories
    needs: [init]
    runs-on: ubuntu-latest
    if: needs.init.outputs.execute_check_and_format == '1'
    environment: development
    strategy:
      fail-fast: false
      max-parallel: ${{ fromJson(needs.init.outputs.threads) }}
      matrix:
        directory: ${{ fromJson(needs.init.outputs.dir_list_dev) }}
    defaults:
      run:
        shell: bash
        working-directory: sources/${{ matrix.directory }}
    steps:
      - name: Cache
        id: cache
        env:
          CACHE_KEY: ${{ needs.init.outputs.cache_key }}
        uses: actions/cache@v3
        with:
          path: sources/
          key: ${{ env.CACHE_KEY }}
      - name: Shell check code
        id: check
        uses: Zidmann/github-actions-template-prototype/ga-shell-check@main
        with:
          working_directory: "sources/${{ matrix.directory }}"

  test-stagging:
    name: Test on stagging
    needs: [init, dev-check]
    runs-on: ubuntu-latest
    if: ${{ (needs.init.outputs.execute_test == '1') && (needs.dev-pr-diff.outputs.pull_request_opened == '0') }}
    environment: testing
    strategy:
      fail-fast: false
      max-parallel: ${{ fromJson(needs.init.outputs.threads) }}
      matrix:
        directory: ${{ fromJson(needs.init.outputs.dir_list_test) }}
    defaults:
      run:
        shell: bash
        working-directory: sources/${{ matrix.directory }}
    env:
      GITHUB_WORKSPACE: ${{ github.workspace }}
    steps:
      - name: Cache
        id: cache
        env:
          CACHE_KEY: ${{ needs.init.outputs.cache_key }}
        uses: actions/cache@v3
        with:
          path: sources/
          key: ${{ env.CACHE_KEY }}
      - name: Deploy on stagging environment
        id: deploy
        env:
          PROJECT_ID: "${{ secrets.PROJECT_ID }}"
          PROJECT_PREFIX: "${{ secrets.PROJECT_PREFIX }}"
          SERVICE_ACCOUNT: "${{ secrets.SERVICE_ACCOUNT }}"
          SERVICE_ACCOUNT_KEY: "${{ secrets.SERVICE_ACCOUNT_KEY }}"
          SSH_PRIVATE_KEY: "${{ secrets.SSH_PRIVATE_KEY }}"
        uses: Zidmann/github-actions-template-prototype/ga-tf-deploy@main
        with:
          project_id: "${{ env.PROJECT_ID }}"
          project_prefix: "${{ env.PROJECT_PREFIX }}"
          service_account: "${{ env.SERVICE_ACCOUNT }}"
          service_account_key: "${{ env.SERVICE_ACCOUNT_KEY }}"
          token_format: "${{ needs.init.outputs.token_format_test }}"
          access_token_lifetime: "${{ needs.init.outputs.access_token_lifetime }}"
          workloadidentity_provider: "${{ needs.init.outputs.workloadidentity_provider_test }}"
          state_key: "${{ needs.init.outputs.sha7 }}"
          suffix_name: "${{ needs.init.outputs.sha7 }}"
          ssh_private_key: "${{ env.SSH_PRIVATE_KEY }}"
          working_directory: "sources/${{ matrix.directory }}"
      - name: Clean stagging environment
        id: clean
        if: always()
        env:
          PROJECT_ID: "${{ secrets.PROJECT_ID }}"
        uses: Zidmann/github-actions-template-prototype/ga-tf-destroy@main
        with:
          init_already_done: "1"
          project_id: "${{ env.PROJECT_ID }}"
          suffix_name: "${{ needs.init.outputs.sha7 }}"
          working_directory: "sources/${{ matrix.directory }}"

  deploy-production:
    name: Deploy on production
    needs: [init, test-stagging]
    runs-on: ubuntu-latest
    if: ${{ (needs.init.outputs.execute_deploy == '1') && (needs.dev-pr-diff.outputs.pull_request_opened == '0') }}
    environment: production
    strategy:
      fail-fast: false
      max-parallel: ${{ fromJson(needs.init.outputs.threads) }}
      matrix:
        directory: ${{ fromJson(needs.init.outputs.dir_list_prod) }}
    defaults:
      run:
        shell: bash
        working-directory: sources/${{ matrix.directory }}
    env:
      GITHUB_WORKSPACE: ${{ github.workspace }}
    steps:
      - name: Cache
        id: cache
        env:
          CACHE_KEY: ${{ needs.init.outputs.cache_key }}
        uses: actions/cache@v3
        with:
          path: sources/
          key: ${{ env.CACHE_KEY }}
      - name: Deploy on production environment
        id: deploy
        env:
          PROJECT_ID: "${{ secrets.PROJECT_ID }}"
          PROJECT_PREFIX: "${{ secrets.PROJECT_PREFIX }}"
          SERVICE_ACCOUNT: "${{ secrets.SERVICE_ACCOUNT }}"
          SERVICE_ACCOUNT_KEY: "${{ secrets.SERVICE_ACCOUNT_KEY }}"
          SSH_PRIVATE_KEY: "${{ secrets.SSH_PRIVATE_KEY }}"
        uses: Zidmann/github-actions-template-prototype/ga-tf-deploy@main
        with:
          project_id: "${{ env.PROJECT_ID }}"
          project_prefix: "${{ env.PROJECT_PREFIX }}"
          service_account: "${{ env.SERVICE_ACCOUNT }}"
          service_account_key: "${{ env.SERVICE_ACCOUNT_KEY }}"
          token_format: "${{ needs.init.outputs.token_format_prod }}"
          access_token_lifetime: "${{ needs.init.outputs.access_token_lifetime }}"
          workloadidentity_provider: "${{ needs.init.outputs.workloadidentity_provider_prod }}"
          state_key: "production"
          ssh_private_key: "${{ env.SSH_PRIVATE_KEY }}"
          working_directory: "sources/${{ matrix.directory }}"
